package net.onelitefeather.minestom.extensions.maven;

import net.onelitefeather.minestom.extensions.processor.ExtensionDescriptor;
import org.apache.maven.artifact.Artifact;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Adds the dependencies declared in the POM to the {@code extension.json} generated by
 * {@code minestom-extensions-processor}.
 *
 * <p>Without this, the coordinates have to be repeated in {@code @ExtensionInfo} next to versions
 * the build already knows — two places to update, one of which goes stale unnoticed.
 *
 * <p>Which dependencies to record is stated explicitly. Deriving them from a scope was tried and
 * rejected: everything a Minestom extension compiles against is {@code provided} — Minestom itself,
 * {@code minestom-extensions}, the annotation processor — and none of those are libraries the
 * extension should resolve at runtime. Guessing produced a descriptor that told the server to
 * download the annotation processor.
 *
 * <p>The version may be left out, and then comes from the project's own dependencies. That is the
 * point of the goal: the coordinate is named once here and versioned once in {@code
 * <dependencies>}, instead of being repeated in the annotation.
 *
 * <pre>{@code
 * <plugin>
 *   <groupId>net.onelitefeather</groupId>
 *   <artifactId>minestom-extensions-maven-plugin</artifactId>
 *   <version>RELEASE_VERSION</version>
 *   <configuration>
 *     <externalDependencies>
 *       <!-- version taken from <dependencies> -->
 *       <externalDependency>org.apache.commons:commons-lang3</externalDependency>
 *       <!-- or pinned here -->
 *       <externalDependency>com.google.guava:guava:33.4.0-jre</externalDependency>
 *     </externalDependencies>
 *   </configuration>
 *   <executions>
 *     <execution>
 *       <goals><goal>describe</goal></goals>
 *     </execution>
 *   </executions>
 * </plugin>
 * }</pre>
 */
@Mojo(name = "describe", defaultPhase = LifecyclePhase.PROCESS_CLASSES, threadSafe = true)
public class ExtensionDescriptorMojo extends AbstractMojo {

    /** The project being built. */
    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /** Directory holding the compiled classes, where the processor wrote the descriptor. */
    @Parameter(defaultValue = "${project.build.outputDirectory}", readonly = true, required = true)
    private File outputDirectory;

    /**
     * Coordinates to record, as {@code group:artifact} or {@code group:artifact:version}. Without a
     * version, it is taken from the project's dependencies.
     */
    @Parameter
    private List<String> externalDependencies = new ArrayList<>();

    /**
     * Repositories the runtime should search, as {@code name=url} entries. When empty, the
     * repositories declared in the POM are used.
     */
    @Parameter
    private Map<String, String> repositories = new LinkedHashMap<>();

    /** Whether the repositories declared in the POM are written into the descriptor. */
    @Parameter(defaultValue = "true")
    private boolean inheritProjectRepositories;

    /** Skips the goal entirely. */
    @Parameter(property = "minestom.extension.skip", defaultValue = "false")
    private boolean skip;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (skip) {
            getLog().info("Skipping extension descriptor");
            return;
        }

        final File file = new File(outputDirectory, "extension.json");
        if (!file.isFile()) {
            if (externalDependencies.isEmpty()) {
                getLog().debug("No descriptor and nothing configured, nothing to do");
                return;
            }
            throw new MojoFailureException(file + " does not exist. Is "
                    + "minestom-extensions-processor configured in <annotationProcessorPaths> of "
                    + "maven-compiler-plugin, and is an entrypoint annotated with @ExtensionInfo?");
        }

        final List<String> artifacts = resolveCoordinates();

        final ExtensionDescriptor descriptor;
        try {
            descriptor = ExtensionDescriptor.fromJson(pristineDescriptor(file));
        } catch (IOException e) {
            throw new MojoExecutionException("Could not read " + file, e);
        } catch (IllegalArgumentException e) {
            throw new MojoFailureException(file + " is not a usable extension descriptor: "
                    + e.getMessage(), e);
        }

        if (artifacts.isEmpty()) {
            // Nothing configured any more. The descriptor still has to be restored to what the
            // processor produced, or coordinates removed from the POM would linger in it.
            writeDescriptor(file, descriptor.toJson());
            getLog().debug("No external dependencies configured");
            return;
        }

        // Whatever @ExtensionInfo already declared stays and wins on a clash: ExtensionDescriptor
        // ignores duplicate coordinates and keeps the first repository seen for a given name.
        descriptor.artifacts(artifacts);
        final List<ExtensionDescriptor.RepositoryEntry> entries = new ArrayList<>();
        resolveRepositories().forEach((name, url) ->
                entries.add(new ExtensionDescriptor.RepositoryEntry(name, url)));
        descriptor.repositories(entries);

        if (descriptor.repositories().isEmpty()) {
            throw new MojoFailureException("The extension declares external dependencies but no "
                    + "repository to resolve them from, so the server would fail to load it. Declare "
                    + "a <repository> in the POM, or configure <repositories> on this plugin.");
        }

        writeDescriptor(file, descriptor.toJson());

        getLog().info("Recorded " + descriptor.artifacts().size() + " external "
                + (descriptor.artifacts().size() == 1 ? "dependency" : "dependencies")
                + " in extension.json");
    }

    /** Writes the descriptor and records it, so the next run can tell its own output apart. */
    private void writeDescriptor(File file, String json) throws MojoExecutionException {
        try {
            Files.writeString(file.toPath(), json, StandardCharsets.UTF_8);
            Files.writeString(lastWrittenFile().toPath(), json, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new MojoExecutionException("Could not write " + file, e);
        }
    }

    /**
     * Returns the descriptor as the annotation processor wrote it, rather than as this goal last
     * left it.
     *
     * <p>The goal writes into the same file it reads, so on a build without {@code clean} — where
     * {@code compile} is up to date and the processor does not run again — it would otherwise read
     * back its own output. Merging into that is not harmless: a coordinate removed from the POM
     * would stay in the descriptor forever, and the server would keep downloading it.
     *
     * <p>So a pristine copy is kept beside the build output. It is refreshed whenever the file in
     * the class output differs from what this goal wrote last, which is exactly the case where the
     * processor has regenerated it.
     */
    private String pristineDescriptor(File descriptor) throws IOException {
        final String current = Files.readString(descriptor.toPath(), StandardCharsets.UTF_8);
        final File lastWritten = lastWrittenFile();
        final File pristine = new File(lastWritten.getParentFile(), "pristine-descriptor.json");

        if (lastWritten.isFile() && pristine.isFile()
                && current.equals(Files.readString(lastWritten.toPath(), StandardCharsets.UTF_8))) {
            // Unchanged since our last run: the processor did not regenerate it.
            return Files.readString(pristine.toPath(), StandardCharsets.UTF_8);
        }

        Files.writeString(pristine.toPath(), current, StandardCharsets.UTF_8);
        return current;
    }

    private File lastWrittenFile() throws IOException {
        final File dir = new File(project.getBuild().getDirectory(), "minestom-extension");
        Files.createDirectories(dir.toPath());
        return new File(dir, "last-written-descriptor.json");
    }

    /**
     * Completes each configured coordinate, filling in a missing version from the project's own
     * dependencies.
     *
     * @throws MojoFailureException if a coordinate is malformed, or has no version and no matching
     *                              project dependency to take one from
     */
    private List<String> resolveCoordinates() throws MojoFailureException {
        final List<String> resolved = new ArrayList<>(externalDependencies.size());

        for (String declared : externalDependencies) {
            final String coordinate = declared.trim();
            final String[] parts = coordinate.split(":");

            if (parts.length == 3) {
                resolved.add(coordinate);
                continue;
            }
            if (parts.length != 2) {
                throw new MojoFailureException("'" + coordinate + "' is not a valid coordinate. "
                        + "Expected group:artifact or group:artifact:version.");
            }

            final String version = versionOf(parts[0], parts[1]);
            if (version == null) {
                throw new MojoFailureException("No version given for '" + coordinate
                        + "' and the project has no such dependency to take one from. Either add it "
                        + "to <dependencies>, or write the version into the coordinate.");
            }
            resolved.add(parts[0] + ":" + parts[1] + ":" + version);
        }
        return resolved;
    }

    private String versionOf(String groupId, String artifactId) {
        for (Artifact artifact : project.getArtifacts()) {
            if (artifact.getGroupId().equals(groupId) && artifact.getArtifactId().equals(artifactId)) {
                return artifact.getVersion();
            }
        }
        return null;
    }

    private Map<String, String> resolveRepositories() {
        final Map<String, String> resolved = new LinkedHashMap<>();
        if (inheritProjectRepositories) {
            project.getRemoteArtifactRepositories().forEach(repository -> {
                final String url = repository.getUrl();
                // A local path means nothing on the server.
                if (url != null && (url.startsWith("http://") || url.startsWith("https://"))) {
                    resolved.put(repository.getId(), url);
                }
            });
        }
        resolved.putAll(repositories);
        // Sorted so the descriptor does not churn between builds.
        return new TreeMap<>(resolved);
    }
}
