package net.minestom.server.extensions;

import com.google.gson.Gson;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Pins the on-disk shape of {@code extension.json} to the fields {@link DiscoveredExtension}
 * actually reads.
 *
 * <p>This exists because the contract has no compiler to enforce it. {@code
 * minestom-extensions-processor} generates the descriptor but deliberately does not depend on this
 * module, so nothing links the names it writes to the fields Gson populates here. And Gson silently
 * ignores JSON members it does not recognise: renaming a field in {@link DiscoveredExtension} would
 * not break a single compilation, every processor test would stay green, and extensions would just
 * start losing that value at runtime.
 *
 * <p>{@code extension-descriptor-contract.json} is the exact output of the processor for a fully
 * populated {@code @ExtensionInfo} - the processor's own test suite asserts it reproduces this file
 * byte for byte. So if either end moves, one of the two suites goes red.
 */
class DescriptorContractTest {

    /** The generated descriptor both modules agree on. */
    static final String CONTRACT_RESOURCE = "/extension-descriptor-contract.json";

    @Test
    @DisplayName("the generated descriptor deserializes into every DiscoveredExtension field")
    void generatedDescriptorPopulatesEveryField() throws IOException {
        final DiscoveredExtension extension = readContract();
        DiscoveredExtension.verifyIntegrity(extension);

        assertAll(
                () -> assertEquals("ContractExtension", extension.getName()),
                () -> assertEquals("com.example.ContractExtension", extension.getEntrypoint()),
                () -> assertEquals("4.2.0", extension.getVersion()),
                // Non-ASCII is escaped as \ uXXXX by the processor; it has to survive the round trip.
                () -> assertArrayEquals(new String[]{"TheMeinerLP", "Jörg Müller"},
                        extension.getAuthors()),
                () -> assertArrayEquals(new String[]{"FirstDependency", "SecondDependency"},
                        extension.getDependencies()));
    }

    @Test
    @DisplayName("the nested externalDependencies structure is populated, not silently dropped")
    void externalDependenciesArePopulated() throws IOException {
        final DiscoveredExtension extension = readContract();
        DiscoveredExtension.verifyIntegrity(extension);

        final DiscoveredExtension.ExternalDependencies external = extension.getExternalDependencies();
        assertNotNull(external, "externalDependencies must not be null after verifyIntegrity");

        assertAll(
                () -> assertArrayEquals(
                        new String[]{"com.google.guava:guava:33.4.0-jre",
                                "org.apache.commons:commons-lang3:3.17.0"},
                        external.artifacts),
                () -> assertEquals(2, external.repositories.length),
                () -> assertEquals("central", external.repositories[0].name),
                () -> assertEquals("https://repo1.maven.org/maven2/", external.repositories[0].url),
                () -> assertEquals("onelitefeather", external.repositories[1].name),
                () -> assertEquals("https://repo.onelitefeather.dev/releases",
                        external.repositories[1].url));
    }

    @Test
    @DisplayName("a descriptor generated by the processor loads successfully")
    void contractDescriptorLoadsSuccessfully() throws IOException {
        final DiscoveredExtension extension = readContract();
        DiscoveredExtension.verifyIntegrity(extension);

        assertEquals(DiscoveredExtension.LoadStatus.LOAD_SUCCESS, extension.loadStatus);
        // meta is not written by the processor and must be defaulted rather than left null.
        assertNotNull(extension.getMeta());
        assertEquals(0, extension.getMeta().size());
    }

    private static DiscoveredExtension readContract() throws IOException {
        try (InputStream in = DescriptorContractTest.class.getResourceAsStream(CONTRACT_RESOURCE)) {
            assertNotNull(in, "missing test resource " + CONTRACT_RESOURCE);
            // Deliberately UTF-8 rather than the platform default: the point of the escaping in the
            // processor is that the file is pure ASCII, so this must not depend on the charset.
            try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
                return new Gson().fromJson(reader, DiscoveredExtension.class);
            }
        }
    }
}
