package net.onelitefeather.minestom.extensions.gradle;

import net.onelitefeather.minestom.extensions.processor.ExtensionDescriptor;
import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFile;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Rewrites the {@code extension.json} produced by the annotation processor, adding the external
 * dependencies declared in the build.
 *
 * <p>The result is written to a separate file rather than over the processor's copy, and the jar is
 * configured to take this one instead. Editing in place would make the task's own output its next
 * input, with a consequence worse than a missed up-to-date check: removing an {@code
 * extensionLibrary} would leave the old coordinate in the descriptor forever, because {@code
 * compileJava} stays up to date and never regenerates the file the task reads.
 */
@DisableCachingByDefault(because = "Writing a few hundred bytes of JSON is cheaper than a cache lookup")
public abstract class ExtensionDescriptorTask extends DefaultTask {

    /**
     * The descriptor generated by {@code minestom-extensions-processor}.
     *
     * @return the property
     */
    @InputFile
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract RegularFileProperty getDescriptor();

    /**
     * Maven coordinates to record, as {@code group:artifact:version}.
     *
     * @return the property
     */
    @Input
    public abstract ListProperty<String> getArtifacts();

    /**
     * Repositories to record, keyed by name.
     *
     * @return the property
     */
    @Input
    public abstract MapProperty<String, String> getRepositories();

    /**
     * Version to record, overriding whatever {@code @ExtensionInfo} declared. Left empty, the
     * annotation's value stands.
     *
     * @return the property
     */
    @Input
    @Optional
    public abstract Property<String> getVersion();

    /**
     * Where the enriched descriptor is written. The jar picks this up in place of the processor's
     * copy.
     *
     * @return the property
     */
    @OutputFile
    public abstract RegularFileProperty getOutput();

    /** Merges the build-declared dependencies into the descriptor. */
    @TaskAction
    public void mergeDescriptor() {
        final List<String> artifacts = getArtifacts().get();
        final Map<String, String> repositories = getRepositories().get();

        final File file = getDescriptor().get().getAsFile();
        final ExtensionDescriptor descriptor;
        try {
            descriptor = ExtensionDescriptor.fromJson(
                    Files.readString(file.toPath(), StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read " + file, e);
        } catch (IllegalArgumentException e) {
            throw new GradleException(file + " is not a usable extension descriptor: "
                    + e.getMessage(), e);
        }

        // The build is the better source for the version: keeping it in the annotation as well means
        // maintaining it twice, and the copy in the source is the one that goes stale.
        if (getVersion().isPresent()) {
            descriptor.version(getVersion().get());
        }

        if (artifacts.isEmpty()) {
            // Nothing to add, but the jar still reads the output copy, so it has to exist.
            write(descriptor.toJson());
            return;
        }

        // Coordinates and repositories already stated in @ExtensionInfo are kept; ExtensionDescriptor
        // ignores duplicates and keeps the first repository declared under a given name, so the
        // annotation wins on a clash.
        descriptor.artifacts(artifacts);
        final List<ExtensionDescriptor.RepositoryEntry> entries = new ArrayList<>();
        repositories.forEach((name, url) ->
                entries.add(new ExtensionDescriptor.RepositoryEntry(name, url)));
        descriptor.repositories(entries);

        if (descriptor.repositories().isEmpty()) {
            throw new GradleException("""
                    The extension declares external dependencies but no repository to resolve them \
                    from, so the server would fail to load it. Declare a repository in the project, \
                    or add one explicitly:

                        minestomExtension {
                            repository("central", "https://repo1.maven.org/maven2/")
                        }""");
        }

        write(descriptor.toJson());

        getLogger().lifecycle("Recorded {} external {} in extension.json",
                descriptor.artifacts().size(),
                descriptor.artifacts().size() == 1 ? "dependency" : "dependencies");
    }

    private void write(String json) {
        final File target = getOutput().get().getAsFile();
        try {
            Files.createDirectories(target.toPath().getParent());
            Files.writeString(target.toPath(), json, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not write " + target, e);
        }
    }
}
